mosa/MOSA-Project

- Source/Korlib/System/Array.cs
- Source/Mosa.Compiler.Framework/CIL/NewarrInstruction.cs
- Source/Mosa.Compiler.Framework/MosaTypeLayout.cs
- Source/Mosa.Compiler.MosaTypeSystem/Metadata/MetadataLoader.cs
- Source/Mosa.Compiler.MosaTypeSystem/Metadata/MetadataResolver.cs
- Source/Mosa.Compiler.MosaTypeSystem/MosaTypeExtension.cs
- Source/Mosa.Compiler.MosaTypeSystem/SignatureName.cs
- Source/Mosa.Compiler.MosaTypeSystem/TypeSystem.cs
- Source/Mosa.Compiler.MosaTypeSystem/Units/MosaProperty.cs
- Source/Mosa.Compiler.MosaTypeSystem/Units/MosaType.cs
- Source/Mosa.Platform.x86/Stages/IRTransformationStage.cs
- Source/Mosa.TestWorld.x86/Mosa.TestWorld.x86.csproj
- Source/Mosa.TestWorld.x86/Tests/ArrayTest.cs
- Source/Mosa.TestWorld.x86/Tests/KernelTest.cs
> Worked on #123

- Source/Mosa.CoolWorld.x86/Boot.cs
- Source/Mosa.CoolWorld.x86/Setup.cs
- Source/Mosa.DeviceSystem/PCIControllerManager.cs
- Source/Mosa.Kernel.x86/CMOS.cs
- Source/Mosa.Platform.Internal.x86/Native.cs
- Source/Mosa.Platform.x86/Instructions/In.cs
- Source/Mosa.Platform.x86/Instructions/Out.cs
- Source/Mosa.Platform.x86/Intrinsic/In16.cs
- Source/Mosa.Platform.x86/Intrinsic/In32.cs
- Source/Mosa.Platform.x86/Intrinsic/In8.cs
- Source/Mosa.Platform.x86/Mosa.Platform.x86.csproj
- Source/Mosa.Platform.x86/Stages/FinalTweakTransformationStage.cs
- Source/Mosa.Platform.x86/Stages/FixedRegisterAssignmentStage.cs
> Fixed X86.In instruction emitter and worked on PCI controller

- Source/Mosa.Tool.Launcher/MainForm.cs
- Source/Mosa.Utility.Launcher/Builder.cs
Fix crash, when no source file was selected
> Launcher: Source file validation

- Source/Mosa.CoolWorld.x86/Boot.cs
- Source/Mosa.HelloWorld.x86/Boot.cs
- Source/Mosa.Tool.Compiler/Compiler.cs
- Update version to 1.4
- Still need new codename
> Update version numbers

- Source/Mosa.Platform.Internal.x86/ExceptionHandlerType.cs
- Source/Mosa.Platform.Internal.x86/MetadataStructures/MetadataPRDefinitionStruct.cs
- Source/Mosa.Platform.Internal.x86/Mosa.Platform.Internal.x86.csproj
- Source/Mosa.Platform.Internal.x86/Runtime.cs
- Source/Mosa.Test.Collection.x86.xUnit/ExceptionHandlingFixture.cs
- Source/Mosa.Test.Collection/ExceptionHandlingTests.cs
> Fix problem with exception handling

- Source/Mosa.Compiler.Framework/CIL/IInstructionDecoder.cs
- Source/Mosa.Compiler.Framework/Register.cs
- Source/Mosa.Compiler.Framework/RegisterAllocator/BaseRegisterAllocator.cs
This should resolve the register allocator bug related to segment registers (#174).
> - Fixed bug in register allocator (fixes #174)

- Source/Mosa.ClassLib/Mosa.ClassLib.csproj
- Source/Mosa.Kernel.x86/Debug.cs
- Source/Mosa.Kernel.x86/Helpers/FlechtersChecksum.cs
- Source/Mosa.Kernel.x86/Mosa.Kernel.x86.csproj
- Moved checksum to Mosa.Kernel.x86
> Fixed build by moving checksum

- Source/Mosa.Compiler.Framework/Operand.cs
- Source/Mosa.TestWorld.x86/Tests/OtherTest.cs
> Bug fix for #189

- Source/Korlib/Korlib.csproj
- Source/Korlib/System.Runtime.Versioning/NonVersionableAttribute.cs
- Source/Korlib/System/CharEnumerator.cs
- Source/Korlib/System/Object.cs
- Source/Korlib/System/String.cs
- Source/Mosa.Compiler.Framework/CIL/UnboxInstruction.cs
- Source/Mosa.Compiler.Framework/Stages/CILTransformationStage.cs
- Fixes VS version checking for Korlib
- Fixes formatting issues caused by incorrectly configured IDE
> Fix issues

- Source/Mosa.Compiler.Framework/IR/VmCall.cs
- Source/Mosa.Compiler.Framework/Stages/CILTransformationStage.cs
- Source/Mosa.Compiler.Framework/Stages/ConvertCompoundStage.cs
- Source/Mosa.Platform.Internal.x86/Runtime.cs
- Source/Mosa.TinyCPUSimulator.TestSystem/TestCompiler.cs
- Source/Mosa.Tool.Explorer/Main.Designer.cs
- Source/Mosa.Utility.Launcher/Options.cs
This is a work in progress. Methods with less than 12 IR instructions or less will be inlined into the calling method. Anything more than 12 will generate compiler errors (bugs!). This commit enables up to 8 IR instructions. It's also single-pass; meaning that not all possible inlining will take place.
> Merging inline optimizations (work in progress)

- Source/Mosa.DeviceDriver/PCI/VideoCard/VMwareSVGAII.cs
- Source/Mosa.DeviceSystem/MasterBootBlock.cs
- Source/Mosa.FileSystem/FAT/FatFileLocation.cs
- Source/Mosa.FileSystem/FAT/FatFileStream.cs
- Source/Mosa.FileSystem/FAT/FatFileSystem.cs
- Source/Mosa.FileSystem/FAT/FatSettings.cs
- Source/Mosa.FileSystem/FAT/VfsDirectory.cs
- Source/Mosa.Tool.CreateBootImage/Program.cs
- Source/Mosa.Tool.Launcher/MainForm.Designer.cs
- Source/Mosa.Tool.Launcher/MainForm.cs
- Source/Mosa.Utility.BootImage/Generator.cs
- Source/Mosa.Utility.BootImage/Mosa.Utility.BootImage.csproj
- Source/Mosa.Utility.BootImage/Syslinux.cs
- Source/Mosa.Utility.Launcher/Builder.cs
- Source/Mosa.Utility.Launcher/FileSystemFormat.cs
- Source/Mosa.Utility.Launcher/Options.cs
- Tools/readme.txt
Due to Syslinux 6.03 on disk image not yet working.
> Set default build to ISO

- Source/Mosa.Platform.x86/Stages/Multiboot0695Stage.cs
- Source/Mosa.Tool.Compiler/Compiler.cs
- Source/Mosa.Tool.Launcher/MainForm.Designer.cs
- Source/Mosa.Tool.Launcher/MainForm.cs
- Source/Mosa.Utility.BootImage/BootFormat.cs
- Source/Mosa.Utility.Launcher/Builder.cs
- Source/Mosa.Utility.Launcher/CheckOptions.cs
- Added support for multiboot video mode
- Added UI options for multiboot video mode
- Added command line options for multiboot video mode
> Added support for Multiboot video

- Source/Korlib/Korlib.csproj
- Source/Korlib/System.Diagnostics/DebuggerBrowsableAttribute.cs
- Source/Korlib/System/Array.cs
- Source/Korlib/System/Char.cs
- Source/Korlib/System/String.cs
- Source/Mosa.CoolWorld.x86/Boot.cs
- Source/Mosa.CoolWorld.x86/Setup.cs
- Source/Mosa.FileSystem/FAT/FatFileSystem.cs
- Source/Mosa.FileSystem/FAT/Find/Any.cs
- Source/Mosa.FileSystem/FAT/Find/ByCluster.cs
- Source/Mosa.FileSystem/FAT/Find/Volume.cs
- Source/Mosa.FileSystem/FAT/Find/WithName.cs
- Source/Mosa.FileSystem/FAT/VfsDirectory.cs
- Source/Mosa.FileSystem/FAT/VfsFile.cs
- Source/Mosa.FileSystem/VFS/DirectoryEntry.cs
- Source/Mosa.FileSystem/VFS/DirectoryNode.cs
- Source/Mosa.FileSystem/VFS/IDirectory.cs
- Source/Mosa.FileSystem/VFS/IVfsNode.cs
- Source/Mosa.FileSystem/VFS/NodeBase.cs
- Source/Mosa.FileSystem/VFS/PathResolver.cs
- Source/Mosa.FileSystem/VFS/PathSplitter.cs
- Minor modifications to Mosa.FileSystem
> - Added new methods to korlib

- Source/Mosa.Compiler.MosaTypeSystem/Metadata/MetadataLoader.cs
> Fix for #273

- Source/Mosa.Compiler.Framework.xUnit/LiveRangeTests.cs
- Source/Mosa.Compiler.Framework/Analysis/SimpleTraceBlockOrder.cs
- Source/Mosa.Compiler.Framework/Analysis/SparseConditionalConstantPropagation.cs
- Source/Mosa.Compiler.Framework/BaseMethodCompilerStage.cs
- Source/Mosa.Compiler.Framework/BasicBlock.cs
- Source/Mosa.Compiler.Framework/BasicBlocks.cs
- Source/Mosa.Compiler.Framework/DelegatePatcher.cs
- Source/Mosa.Compiler.Framework/InstructionLogger.cs
- Source/Mosa.Compiler.Framework/Stages/BlockOrderingStage.cs
- Source/Mosa.Compiler.Framework/Stages/CILDecodingStage.cs
- Source/Mosa.Compiler.Framework/Stages/CodeGenerationStage.cs
- Source/Mosa.Compiler.Framework/Stages/EmptyBlockRemovalStage.cs
- Source/Mosa.Compiler.Framework/Stages/ExceptionPrologueStage.cs
- Source/Mosa.Compiler.Framework/Stages/IRCleanupStage.cs
- Source/Mosa.Compiler.Framework/Stages/InlineEvaluationStage.cs
- Source/Mosa.Compiler.Framework/Stages/TypeInitializerSchedulerStage.cs
- Source/Mosa.Platform.Internal.x86/Mosa.Platform.Internal.x86.csproj
- Source/Mosa.Platform.Internal.x86/Runtime.cs
- Source/Mosa.Platform.Internal.x86/SimpleStackTraceEntry.cs
- Source/Mosa.Platform.Internal.x86/StringBuffer.cs
- Source/Mosa.Platform.x86/Stages/InterruptVectorStage.cs
- Source/Mosa.Platform.x86/Stages/Multiboot0695Stage.cs
- Source/Mosa.Platform.x86/Stages/SSESetupStage.cs
- Source/Mosa.TinyCPUSimulator.Adaptor/SimPowerUpStage.cs
- Source/Mosa.Tool.Explorer/ExplorerMethodCompiler.cs
> - Worked to get inline optimization enabled for methods with exception handlers

- Source/Mosa.Compiler.Framework/Stages/CILTransformationStage.cs
- Source/Mosa.Kernel.x86/ProcessManager.cs
- Source/Mosa.Kernel.x86/TaskManager.cs
- Source/Mosa.Platform.x86/Stages/IRTransformationStage.cs
- Source/Mosa.Platform.x86/Stages/LongOperandTransformationStage.cs
- Source/Mosa.Test.Collection/ValueTypeTests.cs
- Source/Mosa.TinyCPUSimulator/SimCPU.cs
- Added spinlock to process and task managers
- Updated process and task managers to manually setup initials
- Added 32bit, 64bit and 128bit sized processing for TinySim's
Accelerator Functions
- Fixed TestValueTypeVirtualMethod unit test
- Fixed how static field values are loaded
- Closes #282 
- Closes #284
> Various changes and fixes

- Source/Mosa.Platform.x86/Stages/IRTransformationStage.cs
> Fix issue where an incorrect dereference can be created by compiler.

- Source/Mosa.Compiler.Framework/Analysis/BaseDominanceAnalysis.cs
- Source/Mosa.Compiler.Framework/Analysis/SimpleFastDominance.cs
- Source/Mosa.Compiler.Framework/BaseCodeTransformationStage.cs
- Source/Mosa.Compiler.Framework/Context.cs
- Source/Mosa.Compiler.Framework/Mosa.Compiler.Framework.csproj
- Source/Mosa.Compiler.Framework/Operand.cs
- Source/Mosa.Compiler.Framework/Properties/AssemblyInfo.cs
- Source/Mosa.Tool.Launcher/MainForm.cs
- Source/Mosa.UnitTest.Collection.xUnit/GenericInterfaceFixture.cs
- Source/Mosa.UnitTest.Collection.xUnit/GenericMethodFixture.cs
- Source/Mosa.UnitTest.Collection.xUnit/Mosa.UnitTest.Collection.xUnit.csproj
- Source/Mosa.UnitTest.Collection/GenericInterfaceTests.cs
- Source/Mosa.UnitTest.Collection/GenericMethodTests.cs
- Source/Mosa.UnitTest.Collection/Mosa.UnitTest.Collection.csproj
- Source/Mosa.Utility.AOT/AotMethodCompiler.cs
Note: exposes bug(s) with generic methods with one failed test case.
> Added unit tests for Generic Methods

- Source/Mosa.Utility.Launcher/AppLocations.cs
- Source/Mosa.Utility.Launcher/Starter.cs
Also added the gui_debugger option. Bochs launchs with a Debugger than. That is the main purpose of Bochs, isn't it? ;-)
> Bochs Linux compatibility

- Source/Mosa.Platform.x86/Intrinsic/Jmp.cs
- Source/Mosa.Platform.x86/Mosa.Platform.x86.csproj
- Source/Mosa.Runtime.x86/Native.cs
For future Developments, a jmp call with variable adress is requied.
> added jmp intrinsic

- Source/Data/ESP32Instructions.json
> ESP32 Json

- Source/Mosa.Korlib/System.IO/MemoryStream.cs
- Source/Mosa.Korlib/System/Int16.cs
- Source/Mosa.Korlib/System/Int32.cs
- Source/Mosa.Korlib/System/Int64.cs
- Source/Mosa.Korlib/System/String.cs
Int16, Int32, Int64 added Parse and TryParse Methods
> Added Parse and TryParse to all Integer classes

- Source/Mosa.Compiler.MosaTypeSystem/SignatureName.cs
For better GDB, ELF, DWARF and exported EntryPoints, we want customize the SymbolName for better usability
> simplified symbols

- Source/Mosa.Compiler.Framework/CompilerOptions.cs
- Source/Mosa.Tool.Launcher/MainForm.Designer.cs
- Source/Mosa.Tool.Launcher/MainForm.cs
- Source/Mosa.Utility.Launcher/Builder.cs
- Source/Mosa.Utility.Launcher/LauncherOptions.cs
Added Option for explicit only Inline method marked as AggressiveInline. Its only the empty option without a function yet.
> added inline only explit option

- Source/Mosa.Compiler.Extension.Dwarf/DwarfCompilerStage.cs
- Source/Mosa.Compiler.Extension.Dwarf/DwarfDefinitions.cs
Added some documentation and a small fix. This commit should not conflict with your current DWARF-Patch in preparation.
> dwarf improvement

- Source/Mosa.Tool.Explorer/MainForm.Designer.cs
- Source/Mosa.Tool.Explorer/MainForm.cs
- Disable/Enable all optimization at once
- Bugfix while exporting (missing subdirectory)
> improved explorer

- .github/workflows/builds.yml
- .github/workflows/unittests.yml
> fix: using outdated version of msbuild action

- Source/Mosa.Utility.Disassembler/Disassembler.cs
- Source/Mosa.Utility.Disassembler/Mosa.Utility.Disassembler.csproj
@tgiphil : I made the changes I proposed on https://gitter.im/uxmal/reko
> Upgrade to Reko v0.9.3

- Source/Mosa.Tool.Compiler/Properties/launchSettings.json
- Source/Mosa.Tool.Launcher/MainForm.Designer.cs
- Source/Mosa.Tool.Launcher/MainForm.cs
> Fixed minor GUI error

- Source/Mosa.Korlib/System.Collections/Stack.cs
- Source/Mosa.Korlib/System.Globalization/CharUnicodeInfo.cs
- Source/Mosa.Korlib/System.Security/SecurityCriticalAttribute.cs
- Source/Mosa.Korlib/System.Security/SecurityCriticalScope.cs
- Source/Mosa.Korlib/System/Char.cs
I removed most of the unsafe code from 'Char' class and replaced it with working code, among that I had to build a few helper classes as well.
I also implemented a stack version, that needs to be run through unit tests, unsure if stack will work properly its almost a 1:1 port, I am expecting it too, but again about first time doing this.
Let me know your thoughts, thanks.
> Added stack class and fixes to 'Char' class

- Source/Mosa.DeviceDriver/ISA/ACPI.cs
- Source/Mosa.DeviceDriver/ISA/CMOS.cs
- Source/Mosa.DeviceDriver/ISA/PIT.cs
- Source/Mosa.DeviceDriver/Setup.cs
- Source/Mosa.DeviceSystem/HAL.cs
This PR implements the ACPI driver under ISA (not really ISA, but for simplicity's sake). I've also implemented a few changes, like in PIT and CMOS.
To make the ACPI driver possible though, I had to modify the HAL class to make some internal functions public.
> Implement ACPI

- Source/Mosa.Compiler.Framework/Stages/CILTransformationStage.cs
- Source/Mosa.Compiler.Framework/Transform/BaseTransformation.cs
- Source/Mosa.Compiler.Framework/Transform/Manual/ManualTransforms.cs
- Source/Mosa.Compiler.Framework/Transform/Manual/Memory/DoubleStoreParam32.cs
- Source/Mosa.Compiler.Framework/Transform/Manual/Memory/DoubleStoreParam64.cs
- Source/Mosa.Compiler.Framework/Transform/Manual/Memory/DoubleStoreParamR4.cs
- Source/Mosa.Compiler.Framework/Transform/Manual/Memory/DoubleStoreParamR8.cs
> More param load/store optimizations

- Source/Mosa.Compiler.Framework/BaseMethodCompilerStage.cs
- Source/Mosa.Compiler.Framework/Stages/BaseOptimizationStage.cs
This change increase an optimization opportunity that didn't exist before with empty blocks.
> Empty block optimization

- Source/Mosa.Demo.VBEWorld.x86/Boot.cs
- Source/Mosa.Demo.VBEWorld.x86/VBEDisplay.cs
- Source/Mosa.DeviceDriver/PCI/VMware/VMwareSVGA2.cs
- Source/Mosa.DeviceSystem/Color.cs
- Source/Mosa.DeviceSystem/FrameBuffer.cs
- Source/Mosa.DeviceSystem/FrameBuffer16bpp.cs
- Source/Mosa.DeviceSystem/FrameBuffer24bpp.cs
- Source/Mosa.DeviceSystem/FrameBuffer32bpp.cs
- Source/Mosa.DeviceSystem/FrameBuffer8bpp.cs
- Source/Mosa.DeviceSystem/IFrameBuffer.cs
- Source/Mosa.DeviceSystem/IPixelGraphicsDevice.cs
(1)
VMWareSVGA2 driver: bugs fixed, cleaned-up and almost finished. The driver may need 1-2 days more time to be finalized.
(2)
Using VMWare Player (free) or VMWare Workstation ($$$), it can now draw MOSA logo on a graphical screen using 2DFrameBuffer.
The MOSA logo source code has been taken from VBE Demo and it worked on the first try using 2DFrameBuffers.
> VMWareSVGA2 Driver WIP (Work In Progress) as of 02 October 2021

- Compile.bat
- Source/Mosa.DeviceDriver/PCI/VMware/VMwareSVGA2.cs
(1)
Mandolbrot graphics using VMWareSVGA2 has been added.
(2)
Compile.bat doesn't show commands anymore.
> Mandolbrot graphics using VMWareSVGA2 has been added.

- Source/Mosa.Compiler.Framework/Transform/Manual/ManualTransforms.cs
- Source/Mosa.Compiler.Framework/Transform/Manual/Memory/DoubleStoreObject.cs
- Source/Mosa.Compiler.Framework/Transform/Manual/Memory/DoubleStoreParamObject.cs
- Source/Mosa.Compiler.Framework/Transform/Manual/Memory/LoadSignExtend16x32Store16.cs
- Source/Mosa.Compiler.Framework/Transform/Manual/Memory/LoadSignExtend16x64Store16.cs
- Source/Mosa.Compiler.Framework/Transform/Manual/Memory/LoadSignExtend8x32Store8.cs
- Source/Mosa.Compiler.Framework/Transform/Manual/Memory/LoadSignExtend8x64Store8.cs
- Source/Mosa.Compiler.Framework/Transform/Manual/Memory/LoadStoreParamObject.cs
- Source/Mosa.Compiler.Framework/Transform/Manual/Memory/LoadZeroExtend16x32Store16.cs
- Source/Mosa.Compiler.Framework/Transform/Manual/Memory/LoadZeroExtend16x64Store16.cs
- Source/Mosa.Compiler.Framework/Transform/Manual/Memory/LoadZeroExtend8x32Store8.cs
- Source/Mosa.Compiler.Framework/Transform/Manual/Memory/LoadZeroExtend8x64Store8.cs
- Source/Mosa.Compiler.Framework/Transform/Manual/Memory/StoreLoadObject.cs
- Source/Mosa.Compiler.Framework/Transform/Manual/Memory/StoreLoadParamObject.cs
- Source/Mosa.DeviceDriver/ISA/PIT.cs
- Source/Mosa.DeviceDriver/Setup.cs
- Source/Mosa.DeviceSystem/IAudioDevice.cs
- Source/Mosa.DeviceSystem/INetworkDevice.cs
Some cherry-picking from https://github.com/mosa/MOSA-Project/pull/887
> More optimizations and cherry-picking from AnErrupTion

- Source/Mosa.Compiler.Framework/Operand.cs
- Source/Mosa.Compiler.Framework/Stages/BitTrackerStage.cs
- Source/Mosa.UnitTests/SwitchTests.cs
- Source/Mosa.Utility.Disassembler/Disassembler.cs
Also fixed disassembler - it stopped working with last commit.
> Minor update to BitTracker

- Source/Mosa.Compiler.Framework/Compiler.cs
- Source/Mosa.Compiler.Framework/CompilerSettings.cs
- Source/Mosa.Compiler.Framework/Stages/CILDecodingStageV2.cs
- Source/Mosa.Compiler.MosaTypeSystem/MosaTypeExtension.cs
- Source/Mosa.DeviceSystem/Bitmap.cs
- Source/Mosa.Tool.Explorer/MainForm.Designer.cs
- Source/Mosa.Tool.Explorer/MainForm.cs
- Source/Mosa.UnitTests/Basic/LdargaTests.cs
- Source/Mosa.UnitTests/Basic/LdargaTests.tt
- Source/Mosa.UnitTests/Basic/LdlocaTests.cs
- Source/Mosa.UnitTests/Basic/LdlocaTests.tt
> WIP -  CIL Decoder

- Source/Data/X86-Instructions.json
- Source/Mosa.Platform.x86/Instructions/Test32.cs
- Source/Mosa.Platform.x86/Stages/EarlyOptimizationStage.cs
- Source/Mosa.Platform.x86/Stages/PostOptimizationStage.cs
- Source/Mosa.Platform.x86/Transform/Manual/Cmp32ToTest32.cs
- Source/Mosa.Platform.x86/Transform/Manual/Cmp32ToZero.cs
- Source/Mosa.Platform.x86/Transform/Manual/Test32ToZero.cs
- Source/Mosa.UnitTests/Optimization/InterestingTests.cs
This optimization removes unnecessary CMP and TEST instructions.
> Micro X86 Cmp & Test optimizations

- Source/Create-Installer.bat
- Source/Mosa.DeviceSystem/GraphicalConsole.cs
This PR pulls the bug fixes from #976 so that they can be merged early. Changes:
- Improved the graphical console
- Fixed Create-Installer.bat
> Bug fixes from #976

- docs/CNAME
Went too fast and didn't realize I accidentally deleted those files!
> Add CNAME and .nojekyll back

- Source/Data/X64-Instructions.json
- Source/Data/X86-Instructions.json
- Source/Mosa.Platform.x86/Instructions/Adc32.cs
- Source/Mosa.Platform.x86/Instructions/Add32.cs
- Source/Mosa.Platform.x86/Instructions/And32.cs
- Source/Mosa.Platform.x86/Instructions/Cmp32.cs
- Source/Mosa.Platform.x86/Instructions/IMul1o32.cs
- Source/Mosa.Platform.x86/Instructions/IMul32.cs
- Source/Mosa.Platform.x86/Instructions/IMul3o32.cs
- Source/Mosa.Platform.x86/Instructions/Or32.cs
- Source/Mosa.Platform.x86/Instructions/Sbb32.cs
- Source/Mosa.Platform.x86/Instructions/Sub32.cs
- Source/Mosa.Platform.x86/Instructions/Test32.cs
- Source/Mosa.Platform.x86/Instructions/Xor32.cs
- Source/Mosa.Platform.x86/X86.cs
- Source/Mosa.Platform.x86/X86Instructions.cs
- Source/Mosa.Utility.SourceCodeGenerator/BuildCommonInstructionFiles.cs
> Shrink opcodes + IMul

- Source/Mosa.Compiler.Framework/InstructionNode.cs
- Source/Mosa.Compiler.Framework/Operand.cs
- Source/Mosa.Compiler.Framework/RegisterAllocator/BaseRegisterAllocator.cs
- Source/Mosa.Compiler.Framework/Stages/BitTrackerStage.cs
- Source/Mosa.Compiler.Framework/Transforms/Optimizations/Manual/Special/GetLow32From64.cs
- Source/Mosa.sln
> - Promotion Operand (to replace Type in future)

- Source/Mosa.Demo.SVGAWorld.x86/Properties/launchSettings.json
- Source/Mosa.DeviceDriver/ISA/ACPI.cs
- Source/Mosa.Kernel.BareMetal.x86/GDTTable.cs
- Source/Mosa.Kernel.BareMetal.x86/PageTable.cs
- Source/Mosa.Kernel.BareMetal/Boot.cs
- Source/Mosa.Kernel.BareMetal/BootMemory/BootMemoryMap.cs
- Source/Mosa.Kernel.BareMetal/PageTable.cs
- Source/Mosa.Kernel.BareMetal/PhysicalPageAllocator.cs
- Source/Mosa.Korlib/System/String.cs
- Source/Mosa.Utility.Launcher/AppLocationsSettings.cs
- Source/Mosa.Utility.Launcher/Starter.cs
- Made SVGAWorld's launchSettings.json use QEMU instead of VMware Workstation
- Removed unused paths in AppLocationsSettings.cs
- Removed most string concatenation in Starter.cs in favor of StringBuilder
- Made String.Concat handle null values
- Mapped all RAM in BareMetal
> Some bug fixes

- Source/Mosa.Korlib/System.Runtime.CompilerServices/NullableAttribute.cs
- Source/Mosa.UnitTests/Other/SpecificTests.cs
> Fix NullableAttribute Issue

- Source/Mosa.Korlib/System/String.cs
Implements the following:
- `string.Insert`
- `string.Remove`
- `string.Format` (stubbed)
- `string.IsNullOrWhiteSpace`
> More string operations

- Source/Mosa.Compiler.Framework/BaseMethodCompilerStage.cs
- Source/Mosa.Compiler.Framework/Compiler.cs
- Source/Mosa.Compiler.Framework/CompilerStages/CounterFileStage.cs
- Source/Mosa.Compiler.Framework/CompilerStages/MapFileStage.cs
- Source/Mosa.Compiler.Framework/CompilerStages/MethodCompileTimeStage.cs
- Source/Mosa.Compiler.Framework/Counter.cs
- Source/Mosa.Compiler.Framework/Counters.cs
- Source/Mosa.Compiler.Framework/MethodCompiler.cs
- Source/Mosa.Tool.Launcher/MainWindow.axaml.cs
- Source/Mosa.Utility.Configuration/CommandLineArguments.cs
- Source/Mosa.Utility.Configuration/MOSASettings.cs
- Source/Mosa.Utility.Configuration/Name.cs
> Counter Export

- Source/Mosa.Compiler.Framework/Transforms/LowerTo32/Lower32Transforms.cs
- Source/Mosa.Compiler.Framework/Transforms/LowerTo32/Phi64.cs
- Source/Mosa.Compiler.Framework/Transforms/Optimizations/Manual/ManualTransforms.cs
- Source/Mosa.Compiler.Framework/Transforms/Optimizations/Manual/Special/StoreLoadObject.cs
- Source/Mosa.Tool.Explorer/MainForm.Designer.cs
- Source/Mosa.Tool.Explorer/MainForm.cs
- Source/Mosa.Tool.Explorer/MainForm.resx
- Source/Mosa.Utility.Configuration/CommandLineArguments.cs
- Source/Mosa.Utility.Configuration/MOSASettings.cs
- Source/Mosa.Utility.Configuration/Name.cs
Includes a few new compiler debugging features
> Fixed Phi64 Lowering Bug

- Source/Docs/getting-started.rst
Make the getting started docs less confusing by making the commands work with no changes required.
> fix: update getting-started.rst

- Source/Mosa.Tool.Launcher/MainWindow.axaml
- Source/Mosa.Tool.Launcher/MainWindow.axaml.cs
This PR adds a GUI option in Mosa.Tool.Launcher for the new Loop Range Tracker optimization (#1210).
> Mosa.Tool.Launcher: add Loop Range Tracker option

- Source/Mosa.Compiler.Common.xUnit/Mosa.Compiler.Common.xUnit.csproj
- Source/Mosa.Compiler.Framework.xUnit/Mosa.Compiler.Framework.xUnit.csproj
- Source/Mosa.Compiler.Framework/Analysis/LoopDetector.cs
- Source/Mosa.Compiler.Framework/Loop.cs
- Source/Mosa.Compiler.Framework/Stages/Diagnostic/DebugInfoStage.cs
- Source/Mosa.Compiler.Framework/Stages/Diagnostic/DominanceAnalysisStage.cs
- Source/Mosa.Compiler.Framework/Stages/Diagnostic/GraphVizStage.cs
- Source/Mosa.Compiler.Framework/Stages/Diagnostic/LoopAnalysisStage.cs
- Source/Mosa.Compiler.MosaTypeSystem.CLR/Mosa.Compiler.MosaTypeSystem.CLR.csproj
- Source/Mosa.Tool.Bootstrap/Mosa.Tool.Bootstrap.csproj
- Source/Mosa.Tool.Debugger/Mosa.Tool.Debugger.csproj
- Source/Mosa.Tool.Explorer/MainForm.cs
- Source/Mosa.Tool.Explorer/Mosa.Tool.Explorer.csproj
- Source/Mosa.Tool.Launcher/Mosa.Tool.Launcher.csproj
- Source/Mosa.Utility.Disassembler/Mosa.Utility.Disassembler.csproj
- Moved Analysis stages to Compiler namespace
- Added Loop Analysis stage
> Updated NuGet packages

- Source/Mosa.Compiler.Framework/Transforms/Optimizations/Manual/Propagate/Move32Propagate.cs
- Source/Mosa.Compiler.Framework/Transforms/Optimizations/Manual/Propagate/Move64Propagate.cs
- Source/Mosa.Compiler.Framework/Transforms/Optimizations/Manual/Propagate/MoveManagedPointerPropagate.cs
- Source/Mosa.Compiler.Framework/Transforms/Optimizations/Manual/Propagate/MoveObjectPropagate.cs
- Source/Mosa.Compiler.Framework/Transforms/Optimizations/Manual/Propagate/MoveR4Propagate.cs
- Source/Mosa.Compiler.Framework/Transforms/Optimizations/Manual/Propagate/MoveR8Propagate.cs
- Source/Mosa.Compiler.Framework/Transforms/Optimizations/Manual/Propagate/Phi32Propagate.cs
- Source/Mosa.Compiler.Framework/Transforms/Optimizations/Manual/Propagate/Phi64Propagate.cs
- Source/Mosa.Compiler.Framework/Transforms/Optimizations/Manual/Propagate/PhiManagedPointerPropagate.cs
- Source/Mosa.Compiler.Framework/Transforms/Optimizations/Manual/Propagate/PhiObjectPropagate.cs
- Source/Mosa.Compiler.Framework/Transforms/Optimizations/Manual/Propagate/PhiR4Propagate.cs
- Source/Mosa.Compiler.Framework/Transforms/Optimizations/Manual/Propagate/PhiR8Propagate.cs
These changes ensure that physical registers are not move propagated.
> Optimization Fix
