mosa/MOSA-Project

Source/Mosa.ClassLib/FlechtersChecksum.cs, Source/Mosa.ClassLib/Mosa.ClassLib.csproj, Source/Mosa.Kernel.x86/Debug.cs, Source/Mosa.Kernel.x86/Kernel.cs, Source/Mosa.Kernel.x86/Mosa.Kernel.x86.csproj, Source/Mosa.Kernel.x86/PageTable.cs
- Yesterday, i tweaked a little bit the order of the instructions in Kernel.Setup, but one of them caused the crash of HelloWorld. It's now corrected.
- Added debug method, to track memory changes. Useful, when you find out, when memory ares has changes, that should not changed (using wrong pointers, but in memory management, buffer overflow).
=> Corrected order in Kernel.Setup

Source/Mosa.CoolWorld.x86/Boot.cs, Source/Mosa.HelloWorld.x86/Boot.cs, Source/Mosa.Internal/Extensions.cs, Source/Mosa.Kernel.x86/Debug.cs, Source/Mosa.Kernel.x86/ELFHeader.cs, Source/Mosa.Kernel.x86/GDT.cs, Source/Mosa.Kernel.x86/Multiboot.cs, Source/Mosa.Kernel.x86/PageTable.cs, Source/Mosa.Kernel.x86/Panic.cs, Source/Mosa.Platform.Internal.x86/StringBuffer.cs
- Before, only a very small part was accessible via the MultiBoot class, and it was hardcoded via offsets. Now we have access to most of the MultiBoot informations using structs, including the ELF sections.
- We are now able to get the exact position and size of .text and .data segment in the physical memory.
=> Updated MultiBoot

Source/Mosa.Compiler.Linker/BaseLinker.cs, Source/Mosa.Kernel.x86/Multiboot.cs, Source/Mosa.Platform.x86/Intrinsic/GetMultibootEAX.cs, Source/Mosa.Platform.x86/Intrinsic/GetMultibootEBX.cs, Source/Mosa.Platform.x86/MachineCodeEmitter.cs, Source/Mosa.Platform.x86/Stages/Multiboot0695Stage.cs
- Fix multiboot, many uses of its address were straight copies instead
of copy from address
- Fix multiboot asking for more memory than it used
- Added ability to find symbols in linker
- Fixed issue in machine code emitter where it wasn't able to determine
which section a symbol used
=> Fix multiboot, linker, and machine code emitter

Compile.bat, Source/Mosa.Tool.Compiler/Compiler.cs
Workaround due to MOSA compiler issues related to Microsoft's Roslyn .NET Compiler.
=> Changed compile.bat script to use debug build

Source/Mosa.Platform.x86/Architecture.cs, Source/Mosa.Tool.Debugger/MemoryView.cs, Source/Mosa.UnitTest.Engine/UnitTestEngine.cs
- Fixed issue with R8 alignment during calls
- Fixed debugger MemoryView where entering an invalid address would
cause the view to stop working
- Added map output to unit test engine
=> Fix issue with R8 alignment during calls

Source/Mosa.ClassLib/Mosa.ClassLib.csproj, Source/Mosa.Compiler.Framework.xUnit/Mosa.Compiler.Framework.xUnit.csproj, Source/Mosa.DeviceDriver/Mosa.DeviceDriver.csproj, Source/Mosa.DeviceSystem/Mosa.DeviceSystem.csproj, Source/Mosa.FileSystem/Mosa.FileSystem.csproj, Source/Mosa.Kernel.ARMv6/Mosa.Kernel.ARMv6.csproj, Source/Mosa.Kernel.x86/Mosa.Kernel.x86.csproj, Source/Mosa.Korlib/Mosa.Korlib.csproj, Source/Mosa.Platform.ARMv6/Mosa.Platform.ARMv6.csproj, Source/Mosa.Platform.x64/Mosa.Platform.x64.csproj, Source/Mosa.Platform.x86/Mosa.Platform.x86.csproj, Source/Mosa.Runtime.ARMv6/Mosa.Runtime.ARMv6.csproj, Source/Mosa.Runtime.x86/Mosa.Runtime.x86.csproj, Source/Mosa.Runtime/Mosa.Runtime.csproj, Source/Mosa.Tool.Bootstrap/Mosa.Tool.Bootstrap.csproj, Source/Mosa.Tool.Compiler/Mosa.Tool.Compiler.csproj, Source/Mosa.Utility.CodeCompiler/Mosa.Utility.CodeCompiler.csproj
File names on Unix are case-sensitive.
=> Renaming the Microsoft.Sharp.targets file to its correct name-casing.

Source/Mosa.Kernel.x86/Kernel.cs, Source/Mosa.TestWorld.x86/Boot.cs
Initialize GDT before IDT, because IDT Entries requires a valid Segment Selector.
This never happend before, because on fast computers GDT.Setup() was called before a interrupt, for example clock, got triggered.
With that patch, it works with bochs, too (Bochs is generally slower then qemu).
It's only checked with HelloWorld example on Bochs and Qemu
=> IDT race condition with GDT

Source/Mosa.Compiler.Framework/CompilerOptions.cs, Source/Mosa.Compiler.Framework/Linker/BaseLinker.cs, Source/Mosa.Compiler.Framework/Linker/Elf/ElfLinker.cs, Source/Mosa.Compiler.Framework/Linker/Elf/Section.cs, Source/Mosa.Compiler.Framework/MosaCompiler.cs, Source/Mosa.Platform.x86/Intrinsic/Jmp.cs, Source/Mosa.Platform.x86/Mosa.Platform.x86.csproj, Source/Mosa.Runtime.x86/Native.cs, Source/Mosa.Utility.Launcher/Builder.cs, Source/Mosa.Utility.Launcher/Options.cs
This patch mak it possible to add custom sections for the generated elf file, for example binary blobs, custom code, text data, meta data, what ever you want.
Here's an example, how to use it:
```c#
var Options = new Mosa.Utility.Launcher.Options();
Options.CreateExtraSections = () =>
{
return new List<Section>
{
new Section
{
Name = "customdata",
Type = SectionType.ProgBits,
AddressAlignment = 4096,
EmitMethod = (section, writer) =>
{
var data = File.ReadAllBytes("data.bin");
writer.Write(data);
section.Size = (uint)data.Length;
}
}
};
};
```
I would be glad if you would accept this patch. I followed your code convention where possible. Feel free to refactor the code.
=> Patch-010: Add custom sections to elf

Source/Mosa.Compiler.Framework/MosaTypeLayout.cs
The Size property of StructLayout is valid both on Explicit or Sequential.
This fix fixed also the feature of FixedBuffers (e.g. public unsafe fixed byte fieldName[100]).
UnitTests run successful.
=> 013 Respect explicit struct size

Source/Mosa.Compiler.Framework/CompilerOptions.cs, Source/Mosa.Compiler.Framework/Linker/BaseLinker.cs, Source/Mosa.Compiler.Framework/Linker/Elf/ElfLinker.cs, Source/Mosa.Compiler.Framework/MosaCompiler.cs, Source/Mosa.Utility.Launcher/Builder.cs, Source/Mosa.Utility.Launcher/Options.cs
This patch adds the feature to add additional program headers to a ELF file. A strict multiboot loader like `qemu --kernel`-option will only load parts of the ELF specified in the program headers. GRUB/Syslinux load all other section, too, but this is opional and you cannot specify where those sections will be loded.
=> 015-extra-programheaders

Demos/Run-CoolWorld.bat, Demos/Run-HelloWorld.bat, Demos/Run-TestWorld.bat, Demos/unix/Run-CoolWorld.x86.sh, Demos/unix/Run-Demo.x64.sh, Demos/unix/Run-Demo.x86.sh, Demos/unix/Run-HelloWorld.x86.sh, Demos/unix/Run-TestWorld-x64.sh, Demos/unix/Run-TestWorld-x86.sh, Demos/unix/syslinux.cfg, Demos/win/Run-CoolWorld.x86.bat, Demos/win/Run-HelloWorld.x86.bat, Demos/win/Run-TestWorld.x86.bat, Source/Mosa.Tool.Compiler/Compiler.cs, Source/Mosa.Tool.Compiler/Mosa.Tool.Compiler.csproj, Source/Mosa.Tool.Compiler/Options.cs, Source/Mosa.Tool.CreateBootImage/Options.cs, Source/Mosa.Tool.CreateBootImage/Program.cs
With the current Command line tools (Tool.Compiler & Tool.CreateDiskImage) it was impossible to create working boot image. This is fixed now. For now: Please keep the Command Line tools up to date, if you add/change options. Do not focus only on Tool.Launcher.
Secondary, a unix stack was added for the demo scripts.
Now it's possible (again) to compile mosa kernels on unix without using a custom builder. As you know, the Launcher Tool does not work on unix because of the ugly Controls.
=> 017 Fixed Command Line Tools. Added Unix compatibility

Demos/unix/Run-Demo.x64.sh, Demos/unix/Run-TestWorld-x64.sh, Demos/unix/bochs-x64.bxrc, Source/Mosa.Compiler.Framework/Linker/Elf/MachineType.cs, Source/Mosa.Compiler.Framework/Linker/Elf/ProgramHeader.cs, Source/Mosa.Platform.x64/Architecture.cs, Source/Mosa.Tool.Explorer/DisassemblyStage.cs
- Fixed a Bug in ELF64-Header (EntrySize64 had wrong size)
- MachineType IA64 refers to Itanium64, which is wrong. The correct Arch is x64_86. There's no dedicated x64 only. All Bootloaders (syslinux, grub, qemu -kernel) will refuse them to load, if the machine has no Itanium processor.
- Since Architecture.MachineType is for ELF-Type only (Quote from C#-Comment, Architecture.cs:33: `Gets the type of the elf machine`. If not wished, another property must be added), it must be i386, because otherwiese most bootloaders whill refuse loading (grub1, qemu -kernel, syslinux) because they cannot jump directly into x64 code. Forcing jumping into x64 directly from grub2/patches grub2 will restrict the use of mosa very much. ELF needs a small x86 stub. This is like all OS-Kernels are working (Rust, …
=> Make x64 loadable

Demos/unix/Run-Demo.x86.sh, Source/Mosa.Compiler.MosaTypeSystem/MosaModuleLoader.cs
There are cases, where the Resolver will not be able to resolve the assemblis
automaticly, even if they are in the same directory.
(maybe this has todo with linux / specific mono versions?)
So, try to load them manually recursivly first.
The only way without this patch (maybe only on unix / mono?) would be to add ALL assemblies manually to the assembly list, in the order of most nested assemblies first in the list. This is not practicable, of course, because this means massive manual configuration for every different Mosa-OS.
=> 021 fix resolve error

Source/Mosa.Utility.Launcher/AppLocations.cs
When BOCHS variable is invalid (why ever), it will crash on Windows because of Path.GetDirectoryName(BOCHS). Fixed.
=> 029 fix bochs location

Source/Mosa.Compiler.MosaTypeSystem/SignatureName.cs, Source/Mosa.Compiler.MosaTypeSystem/Units/MosaField.cs, Source/Mosa.Compiler.MosaTypeSystem/Units/MosaMethod.cs, Source/Mosa.Compiler.MosaTypeSystem/Units/MosaProperty.cs
As wished, removed global variable. FullName as now no ReturnType by default, and no spaces behind the commas.
Further Suggestion: Add a new Property "SymbolName" to MosaUnit.
=> undo customize smybolnames

Source/Mosa.Compiler.Framework/CompilerOptions.cs, Source/Mosa.Compiler.MosaTypeSystem/TypeSystem.cs, Source/Mosa.Platform.x86/Intrinsic/IRQs.cs, Source/Mosa.Utility.Launcher/Builder.cs, Source/Mosa.Utility.Launcher/LauncherOptions.cs
Added an option to set a custom path to Interrupt name. Reasons:
- Naming Convention specify, namespace and type name should match cs file path. This is not the case if working in another namespace.
- Keeping the namespaces clean, if no functionality of the reference implementation is needed.
At the Moment, IDT is the only class, that forces a specific placement within the namespace. This will forces a using statement at the top of the another accessing cs file, or absolute namespace accessors. The code is not clean in both cases.
=> Specify Interrupt Method

Source/Mosa.Compiler.Extension.Dwarf/DwarfCompilerStage.cs, Source/Mosa.Compiler.Extension.Dwarf/Mosa.Compiler.Extension.Dwarf.csproj
- Ignoring all Lines with value 0xFEEFEE.
- All Line-Warnings are now gone
- Added Line-Number-Warning. There's now no warning anymore, because skipping 0xFEEFEE.
=> fixed DWARF line numbers

appveyor.yml
Reasons:
With CI/CD, we want to check our builds. Often, we have minor changes, and want to quick check them, just to be sure, that even the minor change does not affect the build, but we need to wait for the build.
In 99,9% of the cases, we want to check MS VS219 Build and Mono Build. The MS VS2917 Build is from minor interest. So I have moved them down in the build order list.
=> appveyor build order

Source/Mosa.Korlib/System/IntPtr.cs, Source/Mosa.Runtime/Pointer.cs
Purpose of this change:
While debugging (line numbers) and every-day development (compile time duration), inline should be disabled. Performance critical sections should still be inlined, specially if you never need to step into those functions. A greate example for performance critical section is the Monitor.Enter and spinlock function, where ToInt32 should really be inlined.
=> Optimize Pointer Operations

Source/Mosa.Compiler.Framework/Linker/Elf/ElfLinker.cs
Currently, there's no ":", and the -1 is wrong also.
=> short symbolname fix

Source/Mosa.Tool.Explorer/MainForm.cs, Source/Mosa.Tool.Explorer/Mosa.Tool.Explorer.csproj, Source/Mosa.Utility.Launcher/Builder.cs, Source/Mosa.Utility.Launcher/FileHunter.cs
Reason:
Mosa Luncher Util's huntfor will solve several edge cases, for example if the Tool in folder A, but the requested source file is in folder B. Mosa-Explorer does not respect these situations.
To avoid code duplication, I generalized HuntFor in a separate helper class.
=> use huntfor function in explorer

.gitignore, Launcher.bat
Small things to fix to enhance the "get started" experience.
When executing the `Launch.bat` in the root directory, the Launcher pointed to `Mosa.CoolWorld.x86.exe` instead of the generated `Mosa.Demo.CoolWorld.x86.exe`.
Also the Launcher produces an artifact file `false` which is probably not meant to be committed into source control. I added that as well to the `.gitignore` file.
=> Fix launcher bat

Source/Mosa.Kernel.x86/VBE.cs
A simple typo in VBE class, happens all the time ;)
=> Correct 'OffScreenMemorSize' spelling mistake in VBE.cs

Source/Mosa.Compiler.Framework/Compiler.cs, Source/Mosa.Compiler.Framework/CompilerStages/MetadataStage.cs, Source/Mosa.Compiler.Framework/CompilerVersion.cs, Source/Mosa.Compiler.Framework/Stages/CILDecodingStageV2.cs, Source/Mosa.Compiler.Framework/Stages/CILTransformationStage.cs, Source/Mosa.Korlib/Mosa.Korlib.csproj, Source/Mosa.Korlib/System/Marvin.cs, Source/Mosa.Korlib/System/String.cs, Source/Mosa.Plug.Korlib.x64/System.Threading/InterlockedPlug.cs, Source/Mosa.Plug.Korlib.x64/System.Threading/MonitorPlug.cs, Source/Mosa.Plug.Korlib.x86/System.Threading/InterlockedPlug.cs, Source/Mosa.Plug.Korlib.x86/System.Threading/MonitorPlug.cs, Source/Mosa.Plug.Korlib/System.Runtime.CompilerServices/RuntimeHelpersPlug.cs, Source/Mosa.Plug.Korlib/System/ArrayPlug.cs, Source/Mosa.Runtime.x86/Internal.cs, Source/Mosa.Runtime/Internal.cs, Source/Mosa.Runtime/Pointer.cs
=> New object format and object hashes

Source/Mosa.Runtime/Pointer.cs
This adds the ``++`` and ``--`` operators override for the ``Pointer`` class.
Example:
```cs
Pointer ptr = Pointer.Zero;
ptr++;
// ptr is now 1 instead of 0
ptr--;
// ptr is now 0 instead of 1
```
=> Add ++ and -- operators for Pointer

Source/Mosa.Korlib/System.Runtime.CompilerServices/Unsafe.cs
This adds most of the missing functions to the Unsafe class from ``https://source.dot.net/``.
Not tested but most likely working as it just calls the other, already implemented functions.
=> Mostly complete Unsafe class

Source/Mosa.Demo.VBEWorld.x86/Boot.cs, Source/Mosa.Demo.VBEWorld.x86/HAL/Hardware.cs, Source/Mosa.Demo.VBEWorld.x86/HAL/X86IOPort.cs, Source/Mosa.DeviceDriver/ISA/ACPI.cs, Source/Mosa.DeviceDriver/ISA/StandardMouse.cs, Source/Mosa.DeviceDriver/Setup.cs, Source/Mosa.DeviceSystem/FrameBuffer.cs, Source/Mosa.DeviceSystem/FrameBuffer16bpp.cs, Source/Mosa.DeviceSystem/FrameBuffer24bpp.cs, Source/Mosa.DeviceSystem/FrameBuffer32bpp.cs, Source/Mosa.DeviceSystem/FrameBuffer8bpp.cs, Source/Mosa.DeviceSystem/IFrameBuffer.cs, Source/Mosa.DeviceSystem/IMouseDevice.cs, Source/Mosa.Runtime/Internal.cs
This is a pull request containing the following changes:
- Double buffering implemented in all framebuffers (along with a new Clear() method)
**This required me to add a parameter ``value`` in ``Internal.MemoryClear`` (which is 0 by default anyways so it won't break anything). Tell me if that causes any problems.**
- PS/2 mouse implemented
- Fixes in ACPI driver for device status
I've also modified the VBEWorld demo so that the double buffering and mouse can be tested.
=> Double buffering, PS/2 mouse and ACPI fixes

Source/Mosa.Compiler.Common/Configuration/Property.cs, Source/Mosa.Compiler.Common/StringExtension.cs, Source/Mosa.Compiler.Framework/Linker/MosaLinker.cs, Source/Mosa.Platform.x64/Architecture.cs, Source/Mosa.Platform.x86/Architecture.cs, Source/Mosa.Tool.Debugger/MainForm.cs, Source/Mosa.Tool.Debugger/Views/MethodParametersView.cs, Source/Mosa.Tool.Debugger/Views/StackFrameView.cs, Source/Mosa.Tool.Explorer/MainForm.cs, Source/Mosa.Tool.Launcher/MainForm.cs, Source/Mosa.Utility.BootImage/Generator.cs, Source/Mosa.Utility.BootImage/Syslinux.cs, Source/Mosa.Utility.Disassembler/Disassembler.cs, Source/Mosa.Utility.Launcher/BaseLauncher.cs, Source/Mosa.Utility.Launcher/CheckOptions.cs, Source/Mosa.Utility.SourceCodeGenerator/BuildCommonInstructionFiles.cs, Source/Mosa.Utility.SourceCodeGenerator/TransformExpressions/InstructionParser.cs, Source/Mosa.Utility.UnitTests/UnitTestEngine.cs, Source/Mosa.Workspace.FileSystem.Debug/Program.cs
After compiling on Windows 10 21H1 with Dotnet Core 5.0 (latest version as of today) regional settings (Turkish regional setting) were causing problems with the filenames including "i" character, because in Turkish we have four different characters for "i".
"ı" (lowercase), "I" (uppercase), "i" (lowercase), "İ" (uppercase). 
For example, the launcher was producing "*.ımg" files, which can't be launched by QEMU.
At same time, when inspected with WinImage, the "*.ımg" files included embedded filenames like "ma0n.exe", "ldl0nux.sys", "sysl0nux.cfg", etc...
The patch fixes these problems without needing to change the regional settings by using ToLowerInvariant() and ToUpperInvariant() string functions in an ASCII like manner.
=> ToLower() => ToLowerInvariant() & ToUpper() => ToUpperInvariant() changes

Source/Mosa.Korlib/System.Collections/Queue.cs, Source/Mosa.Korlib/System/Array.cs, Source/Mosa.Plug.Korlib/System/ArrayPlug.cs
This implements the non-generic Queue (aka the one in System.Collections).
To make it work I also had to implement Array.Clear(), which I did successfully.
**However**, the `TypeDefinition` class, or more specifically (I don't know if it applies to other properties or not) the `Size` property, doesn't work, it just kernel panics. Maybe it's because of the recent changes in the object headers, but it's worth looking into.
=> Implement non-generic Queue

Source/Mosa.Runtime/Internal.cs
(1)
Mosa.Runtime.Internal => Memory operations should be up to 2x-4x times faster.
=> Mosa.Runtime.Internal => Memory operations should be up to 2x-4x times faster.

Source/Mosa.DeviceDriver/PCI/VMware/VMwareSVGA2.cs, Source/Mosa.Kernel.BareMetal.ARMv8A32/PlatformPlug.cs, Source/Mosa.Kernel.BareMetal.x64/PlatformPlug.cs, Source/Mosa.Kernel.BareMetal.x86/GDTTable.cs, Source/Mosa.Kernel.BareMetal.x86/PageTable.cs, Source/Mosa.Kernel.BareMetal.x86/PlatformPlug.cs, Source/Mosa.Kernel.BareMetal/BootMemory/BootMemoryMap.cs, Source/Mosa.Kernel.BareMetal/Platform.cs, Source/Mosa.Utility.Launcher/AppLocationsSettings.cs
- Fixed bugs in BareMetal preventing it from booting
- Fixed a bug in the VirtualBox app location where, on Linux, it wouldn't find VBoxManage because it wasn't properly capitalized
- Removed ``vmworkstation`` in the VMware Workstation app location since it is never named that way
- Fixed a bug in the VMware SVGA II driver where the device was being enabled even without any mode set
=> BareMetal, app locations and VMware SVGA II bug fixes

Source/Mosa.Templates/templates/Mosa.Starter.sln
Split from #1160. Apparently Visual Studio and the dotnet CLI tool don't recognize projects that aren't in the top directory even though a solution file exists, this PR fixes that.
=> Fix template for VS and CLI

Source/Mosa.Korlib/System/Byte.cs, Source/Mosa.Korlib/System/Int16.cs, Source/Mosa.Korlib/System/Int32.cs, Source/Mosa.Korlib/System/Numbers.cs, Source/Mosa.Korlib/System/SByte.cs, Source/Mosa.Korlib/System/UInt16.cs, Source/Mosa.Korlib/System/UInt32.cs
unsafe static string CreateString(uint value,
seemed to be used for signed types as well, and that doesnt work ( if value < 0 ) will never executed.
=> Moved the int.ToString(uvalue) to Numbers.cs

Source/Mosa.BareMetal.HelloWorld.ARM32/Boot.cs, Source/Mosa.BareMetal.HelloWorld.ARM32/Mosa.BareMetal.HelloWorld.ARM32.csproj, Source/Mosa.Compiler.ARM32/Architecture.cs, Source/Mosa.Compiler.ARM32/Transforms/FloatingTweaks/ConvertR4ToU32.cs, Source/Mosa.Compiler.ARM32/Transforms/FloatingTweaks/ConvertR8ToU32.cs, Source/Mosa.Compiler.ARM32/Transforms/FloatingTweaks/ConvertU32ToR8.cs, Source/Mosa.Compiler.ARM32/Transforms/FloatingTweaks/FloatingTweakTransforms.cs, Source/Mosa.Compiler.ARM32/Transforms/FloatingTweaks/RemR4NotSupported.cs, Source/Mosa.Compiler.ARM32/Transforms/FloatingTweaks/RemR8NotSupported.cs, Source/Mosa.Kernel.BareMetal.ARM32/PlatformPlug.cs, Source/Mosa.Kernel.BareMetal.ARM64/PlatformPlug.cs, Source/Mosa.Kernel.BareMetal/PageFrameAllocator.cs, Source/Mosa.Plug.Korlib.ARM32/System.Threading/InterlockedPlug.cs, Source/Mosa.Plug.Korlib.ARM32/System.Threading/MonitorPlug.cs, Source/Mosa.Plug.Korlib.ARM32/System/Math.CoreCLR.cs, Source/Mosa.Plug.Korlib.ARM32/System/MathF.CoreCLR.cs, Source/Mosa.Tool.Explorer/MainForm.cs, Source/Mosa.Tool.Launcher/MainWindow.axaml.cs, Source/Mosa.Utility.Configuration/MOSASettings.cs, Source/Mosa.Utility.Launcher/Starter.cs
=> Expanding ARM32 Support

Source/Mosa.DeviceSystem/AddressRegion.cs, Source/Mosa.DeviceSystem/BaseDeviceConfiguration.cs, Source/Mosa.DeviceSystem/BaseDeviceDriver.cs, Source/Mosa.DeviceSystem/BaseService.cs, Source/Mosa.DeviceSystem/CHS.cs, Source/Mosa.DeviceSystem/ConstrainedPointer.cs, Source/Mosa.DeviceSystem/DataBlock.cs, Source/Mosa.DeviceSystem/DeviceStatus.cs, Source/Mosa.DeviceSystem/DiskDeviceDriver.cs, Source/Mosa.DeviceSystem/GenericPartition.cs, Source/Mosa.DeviceSystem/HAL.cs, Source/Mosa.DeviceSystem/HardwareResources.cs, Source/Mosa.DeviceSystem/IOPort.cs, Source/Mosa.DeviceSystem/MasterBootBlock.cs, Source/Mosa.DeviceSystem/MouseState.cs, Source/Mosa.DeviceSystem/PartitionDeviceDriver.cs, Source/Mosa.DeviceSystem/ServiceManager.cs, Source/Mosa.DeviceSystem/Services/DiskDeviceService.cs
This PR mainly focuses on code style refactorings. The following were done:
- Fold functions with only one statement or expression into one-line
- Fold statements and expressions with empty blocks into one-line
- Trailing commas were removed (e.g. in enums)
- Use pattern matching wherever possible
- Braces were removed in blocks that only had one expression (which was put on a new line if not already)
- The "this" reference has been removed in places where it wasn't needed
- The "var" type inference for variables was used in more places were adequate (e.g. it didn't require casting)
- Fields and functions were reordered when needed, so that private ones are always after public ones
- In adequate places, fields were made public and/or into properties (to better indicate that there's an …
=> Mosa.DeviceSystem: code style refactoring

Source/Mosa.DeviceDriver/ISA/ACPI/ACPIDriver.cs, Source/Mosa.DeviceDriver/ISA/IDEController.cs, Source/Mosa.DeviceDriver/ISA/ISABus.cs, Source/Mosa.DeviceDriver/ISA/PCIController.cs, Source/Mosa.DeviceDriver/ISA/StandardMouse.cs, Source/Mosa.DeviceDriver/PCI/GenericHostBridgeController.cs, Source/Mosa.DeviceDriver/PCI/Intel/Intel440FX.cs, Source/Mosa.DeviceDriver/PCI/Intel/Intel4SeriesChipsetDRAMController.cs, Source/Mosa.DeviceDriver/PCI/Intel/Intel4SeriesChipsetIntegratedGraphicsController.cs, Source/Mosa.DeviceDriver/PCI/Intel/Intel4SeriesChipsetIntegratedGraphicsController2E13.cs, Source/Mosa.DeviceDriver/PCI/Intel/Intel4SeriesChipsetPCIExpressRootPort.cs, Source/Mosa.DeviceDriver/PCI/Intel/IntelPIIX3.cs, Source/Mosa.DeviceDriver/PCI/Intel/IntelPIIX4.cs, Source/Mosa.DeviceDriver/PCI/Intel/PCIIDEInterface.cs, Source/Mosa.DeviceDriver/PCI/Intel/QuarkSoC/IntelGPIOController.cs, Source/Mosa.DeviceDriver/PCI/Intel/QuarkSoC/IntelHSUART.cs, Source/Mosa.DeviceDriver/PCI/VMware/VMwareSVGA2.cs, Source/Mosa.DeviceDriver/PCI/VirtIO/VirtIOGPU.cs, Source/Mosa.DeviceDriver/ScanCodeMap/HU.cs, Source/Mosa.DeviceDriver/ScanCodeMap/US.cs, Source/Mosa.DeviceDriver/Setup.cs, Source/Mosa.DeviceDriver/X86System.cs, Source/Mosa.DeviceSystem/Services/PCService.cs
This PR focuses on refactoring the code style throughout the project. The following changes were done, wherever possible:
- Fold functions into expression bodies (one line)
- Put expression body arrow on the previous line if it's split in multiple
- Make protected and internal structs, fields and functions private (and those were appropriately renamed to fit naming conventions)
- Fields were made readonly
- Enums were unfolded into multiple lines
- Braces of single line blocks were removed
- Braces of empty blocks were put onto the same line as the statement/expression
- The "var" type inference was used for defining variables
- Some commented code was removed (mostly debug printing code)
- A space was prepended to the contents of comments explaining something, whereas spaces were removed …
=> Mosa.DeviceDriver: code style refactoring

Source/Mosa.DeviceDriver/ISA/ACPI/ACPIDriver.cs, Source/Mosa.DeviceDriver/ISA/ACPI/ACPISDTHeader.cs, Source/Mosa.DeviceDriver/ISA/ACPI/FADT.cs, Source/Mosa.DeviceDriver/ISA/ACPI/GenericAddressStructure.cs, Source/Mosa.DeviceDriver/ISA/ACPI/IOAPICEntry.cs, Source/Mosa.DeviceDriver/ISA/ACPI/LongLocalAPICEntry.cs, Source/Mosa.DeviceDriver/ISA/ACPI/MADT.cs, Source/Mosa.DeviceDriver/ISA/ACPI/MADTEntry.cs, Source/Mosa.DeviceDriver/ISA/ACPI/ProcessorLocalAPICEntry.cs, Source/Mosa.DeviceDriver/ISA/ACPI/RSDPDescriptor.cs, Source/Mosa.DeviceDriver/ISA/ACPI/RSDPDescriptor20.cs, Source/Mosa.DeviceDriver/ISA/ACPI/RSDT.cs, Source/Mosa.DeviceDriver/ISA/ACPI/XSDT.cs, Source/Mosa.DeviceDriver/ISA/IDEController.cs, Source/Mosa.DeviceDriver/ISA/ISABus.cs, Source/Mosa.DeviceDriver/ISA/PCIController.cs, Source/Mosa.DeviceDriver/ISA/StandardKeyboard.cs, Source/Mosa.DeviceDriver/ISA/StandardMouse.cs, Source/Mosa.DeviceDriver/PCI/VMware/VMwareSVGA2.cs, Source/Mosa.DeviceDriver/ScanCodeMap/HU.cs, Source/Mosa.DeviceDriver/ScanCodeMap/US.cs, Source/Mosa.DeviceDriver/Setup.cs, Source/Mosa.DeviceSystem/Framework/DeviceBusType.cs, Source/Mosa.DeviceSystem/Framework/Generic/GenericDeviceDriverRegistryEntry.cs, Source/Mosa.DeviceSystem/Services/PCService.cs, Source/Mosa.Runtime/Pointer.cs
This PR focuses on various improvements (like bug fixes) throughout the Mosa.DeviceDriver project. The following changes were done:
- Put references to links in comments after the namespace
- In PCIController, the Definitions region was removed since it only contained 1 field
- The Mosa.Runtime.Pointer struct was made readonly to fix some potential struct copying for ACPI structs
- In VMwareSVGA2:
- Private fields were put after the public frame buffer field for consistency
- The private vramSize field has been removed since it was unused
- In ACPIDriver:
- Variables and private fields were renamed to better match naming conventions
- Some if conditions were inverted to reduce nesting
- The Setup() function was removed and the code was put in the Initialize() function
- In the ACPI sister …
=> Mosa.DeviceDriver: various improvements

Source/Mosa.Compiler.Framework/MosaCompiler.cs, Source/Mosa.Utility.Configuration/AppLocationsSettings.cs, Source/Mosa.Utility.Launcher/BaseLauncher.cs, Source/Mosa.Utility.UnitTests/UnitTestSystem.cs
This PR reverts the previous settings changes done in #1189, and fixes a bug where the app location search code would search recursively for the executables, even though we should be defining in which exact directories it should search.
=> Revert previous settings changes + don't recursively search for file

Source/Mosa.DeviceDriver/ACPI/ACPIDriver.cs, Source/Mosa.DeviceDriver/ACPI/ACPISDTHeader.cs, Source/Mosa.DeviceDriver/ACPI/FADT.cs, Source/Mosa.DeviceDriver/ACPI/GenericAddressStructure.cs, Source/Mosa.DeviceDriver/ACPI/IOAPICEntry.cs, Source/Mosa.DeviceDriver/ACPI/LongLocalAPICEntry.cs, Source/Mosa.DeviceDriver/ACPI/MADT.cs, Source/Mosa.DeviceDriver/ACPI/MADTEntry.cs, Source/Mosa.DeviceDriver/ACPI/ProcessorLocalAPICEntry.cs, Source/Mosa.DeviceDriver/ACPI/RSDPDescriptor.cs, Source/Mosa.DeviceDriver/ACPI/RSDPDescriptor20.cs, Source/Mosa.DeviceDriver/ACPI/RSDT.cs, Source/Mosa.DeviceDriver/ACPI/XSDT.cs, Source/Mosa.DeviceDriver/PCI/VirtIO/Devices/VirtIOGPU.cs, Source/Mosa.DeviceDriver/PCI/VirtIO/VirtIOConfigurationCapabilities.cs, Source/Mosa.DeviceDriver/PCI/VirtIO/VirtIODevice.cs, Source/Mosa.DeviceDriver/PCI/VirtIO/VirtIOFeatures.cs, Source/Mosa.DeviceDriver/PCI/VirtIO/VirtIOFlags.cs, Source/Mosa.DeviceDriver/PCI/VirtIO/VirtIOPCICommonConfiguration.cs, Source/Mosa.DeviceDriver/PCI/VirtIO/VirtIOQueue.cs, Source/Mosa.DeviceDriver/PCI/VirtIO/VirtIOQueueAvailableRing.cs, Source/Mosa.DeviceDriver/PCI/VirtIO/VirtIOQueueDescriptor.cs, Source/Mosa.DeviceDriver/PCI/VirtIO/VirtIOQueueDescriptorFlags.cs, Source/Mosa.DeviceDriver/PCI/VirtIO/VirtIOQueueUsedRing.cs, Source/Mosa.DeviceDriver/Setup.cs
This PR focuses on refactoring the structure of the Mosa.DeviceDriver project. It's pretty minor, the following changes were done:
- Mosa.DeviceDriver.ISA.ACPI => Mosa.DeviceDriver.ACPI
- Mosa.DeviceDriver.PCI.VirtIO => Mosa.DeviceDriver.PCI.VirtIO.Devices
- Mosa.DeviceSystem.VirtIO => Mosa.DeviceDriver.PCI.VirtIO
=> Mosa.DeviceDriver: structural refactoring

Source/Mosa.DeviceDriver/ISA/IDEController.cs, Source/Mosa.DeviceDriver/ISA/ISABus.cs, Source/Mosa.DeviceDriver/ISA/PCIController.cs, Source/Mosa.DeviceDriver/ScanCodeMap/HU.cs
This PR removes all pointless XML comments found in the Mosa.DeviceDriver, which were completely forgotten about in my previous PR. (Whoops!)
=> Mosa.DeviceDriver: remove pointless XML comments

Source/Mosa.BareMetal.HelloWorld/Apps/ShowPCI.cs, Source/Mosa.DeviceDriver/ISA/PCIController.cs, Source/Mosa.DeviceDriver/PCI/VirtIO/VirtIODevice.cs, Source/Mosa.DeviceSystem/Framework/BaseDeviceConfiguration.cs, Source/Mosa.DeviceSystem/HardwareAbstraction/HAL.cs, Source/Mosa.DeviceSystem/PCI/IPCIController.cs, Source/Mosa.DeviceSystem/PCI/PCIDeviceConfiguration.cs, Source/Mosa.DeviceSystem/Services/DeviceService.cs, Source/Mosa.DeviceSystem/Services/PCIDeviceService.cs
Hello! This PR is the final part of refactoring the PCI subsystem. This last part focuses on changing the role of the ``PCIDevice`` class to be a configuration instead of a device driver. Some additional, small code style changes were done, as well as 2 encapsulation changes in the ``HAL`` class.
=> PCI framework refactor: part 3

Source/Mosa.Linux.sln, Source/Mosa.Tool.Explorer.Avalonia/App.axaml, Source/Mosa.Tool.Explorer.Avalonia/App.axaml.cs, Source/Mosa.Tool.Explorer.Avalonia/CompilerData.cs, Source/Mosa.Tool.Explorer.Avalonia/CompilerStage/ExplorerMethodCompileTimeStage.cs, Source/Mosa.Tool.Explorer.Avalonia/CounterEntry.cs, Source/Mosa.Tool.Explorer.Avalonia/MainWindow.axaml, Source/Mosa.Tool.Explorer.Avalonia/MainWindow.axaml.cs, Source/Mosa.Tool.Explorer.Avalonia/MethodData.cs, Source/Mosa.Tool.Explorer.Avalonia/MethodStore.cs, Source/Mosa.Tool.Explorer.Avalonia/Mosa.Tool.Explorer.Avalonia.csproj, Source/Mosa.Tool.Explorer.Avalonia/Program.cs, Source/Mosa.Tool.Explorer.Avalonia/Stages/DebugInfoStage.cs, Source/Mosa.Tool.Explorer.Avalonia/Stages/DisassemblyStage.cs, Source/Mosa.Tool.Explorer.Avalonia/Stages/DominanceOutputStage.cs, Source/Mosa.Tool.Explorer.Avalonia/Stages/GraphVizStage.cs, Source/Mosa.Tool.Explorer.Avalonia/TransformEntry.cs, Source/Mosa.Tool.Explorer.Avalonia/TypeSystemTree.cs, Source/Mosa.Tool.Explorer.Avalonia/Utils.cs, Source/Mosa.Tool.Explorer.Avalonia/app.manifest, Source/Mosa.sln
This PR ports the Explorer tool to Avalonia. Currently, both the Windows Forms and the Avalonia versions coexist as the Avalonia version needs some more polish (most notably visual fixes, and the fact that it uses a pre-release version of Avalonia), but functionality is complete. Once it's been polished, the old tool will be removed and the `.Avalonia` suffix will be removed from the project.
=> Mosa.Tool.Explorer: Port to Avalonia

Source/.editorconfig, Source/Mosa.Utility.Launcher/BaseLauncher.cs, Source/Mosa.Utility.Launcher/Builder.cs, Source/Mosa.Utility.Launcher/SimpleTCP.cs, Source/Mosa.Utility.Launcher/Starter.cs
Hello! This PR makes code style changes throughout the Mosa.Utility.Launcher project in order to improve consistency with other projects. The following changes were done:
- The space shift when putting braces after a `case` statement has now been removed as a ReSharper rule
- Code after a statement (like `if`) was put on a separate line if not already the case
- Method bodies were transformed into expression bodies whenever possible
- Null-coalescing operators were used whenever possible
- Braces around statements were removed if the containing block had only 1 line of code
- Commented code was removed
- Variables whose name didn't give any more useful insight into what it is were inlined (e.g. `var arg = "convert -f raw [...]";`)
- Strings that were too long (like in …
=> Mosa.Utility.Launcher: Code style changes

Source/Mosa.Tool.Debugger/Views/InstructionView.cs, Source/Mosa.Tool.Debugger/Views/MethodView.cs, Source/Mosa.Tool.Debugger/Views/StatusView.cs, Source/Mosa.Tool.Debugger/Views/TraceView.cs, Source/Mosa.Tool.Explorer.Avalonia/Stages/DisassemblyStage.cs, Source/Mosa.Tool.Explorer/Stages/DisassemblyStage.cs, Source/Mosa.Utility.Disassembler/DecodedInstruction.cs, Source/Mosa.Utility.Disassembler/Disassembler.cs, Source/Mosa.Utility.Launcher/Builder.cs
This PR drastically improves the disassembly speed when using Reko (a.k.a. the `-output-asm` CLI argument). The main problem was that the MOSA `Disassembler` class would:
- Read every disassembled instruction from the list created by the Reko library
- Create a whole new list with a few modifications in the string representation
- Read every instruction from that newly created list, the most common scenario being to write them into a file
This is indeed much slower, so this PR fixes it by simply having a `DecodeNext()` method in the `Disassembler` class, which makes it act like an enumerator.
=> Improve Reko disassembly speed

Source/Mosa.Compiler.Framework/Compiler.cs, Source/Mosa.Compiler.Framework/CompilerStages/LinkerEmitStage.cs, Source/Mosa.Compiler.Framework/CompilerStages/LinkerLayoutStage.cs, Source/Mosa.Compiler.Framework/Counters.cs, Source/Mosa.Compiler.Framework/MethodCompiler.cs, Source/Mosa.Compiler.Framework/MethodScanner.cs
=> Added compiler counters

Source/Mosa.Templates/templates/.template.config/dotnetcli.host.json, Source/Mosa.Templates/templates/.template.config/ide.host.json, Source/Mosa.Templates/templates/.template.config/template.json, Source/Mosa.Templates/templates/Mosa.Starter/Mosa.Starter.csproj, Source/Mosa.Tool.Bootstrap/Mosa.Tool.Bootstrap.csproj, Source/Mosa.Tool.Explorer.Avalonia/Mosa.Tool.Explorer.Avalonia.csproj, Source/Mosa.Tool.Launcher/Mosa.Tool.Launcher.csproj, Source/Mosa.Utility.Configuration/MOSASettings.cs
- Updated Avalonia to 11.1.3
- Fixed a settings bug using the Windows registry where the application would crash if the setting wasn't found
- Added a new "Bundle QEMU for Windows" option in the template, which uses Mosa.Tools.Package.Qemu instead of Mosa.Tools.Package
=> Improve template & fix settings bug

Source/Mosa.TinyCoreLib/Internal/Impl.cs, Source/Mosa.TinyCoreLib/Internal/IntrinsicAttribute.cs, Source/Mosa.TinyCoreLib/System.Buffers/MemoryHandle.cs, Source/Mosa.TinyCoreLib/System.Diagnostics/Debug.cs, Source/Mosa.TinyCoreLib/System.Reflection/ConstructorInfo.cs, Source/Mosa.TinyCoreLib/System.Reflection/CustomAttributeData.cs, Source/Mosa.TinyCoreLib/System.Reflection/FieldInfo.cs, Source/Mosa.TinyCoreLib/System.Reflection/IntrospectionExtensions.cs, Source/Mosa.TinyCoreLib/System.Reflection/MethodBase.cs, Source/Mosa.TinyCoreLib/System.Reflection/ParameterInfo.cs, Source/Mosa.TinyCoreLib/System.Reflection/PropertyInfo.cs, Source/Mosa.TinyCoreLib/System.Runtime.CompilerServices/RuntimeHelpers.cs, Source/Mosa.TinyCoreLib/System.Runtime.Intrinsics.X86/Bmi1.cs, Source/Mosa.TinyCoreLib/System.Runtime.Intrinsics.X86/Lzcnt.cs, Source/Mosa.TinyCoreLib/System.Runtime.Intrinsics.X86/Popcnt.cs, Source/Mosa.TinyCoreLib/System/ConsoleKeyInfo.cs, Source/Mosa.TinyCoreLib/System/HashCode.cs, Source/Mosa.TinyCoreLib/System/Object.cs, Source/Mosa.TinyCoreLib/System/Void.cs
Hello! This PR implements various small methods, fields, etc. that were implemented in Mosa.Korlib. Namely, it implements them in the following classes:
**Internal**
- Impl (for platform-specific methods)
- IntrinsicAttribute (for the compiler)
**System**
- ConsoleKeyInfo
- HashCode
- Object
- Void
**System.Buffers**
- MemoryHandle
**System.Diagnostics**
- Debug
**System.Reflection**
- ConstructorInfo
- CustomAttributeData
- FieldInfo
- IntrospectionExtensions
- MethodBase
- ParameterInfo
- PropertyInfo
**System.Runtime.CompilerServices**
- RuntimeHelpers
**System.Runtime.Intrinsics.X86**
- Bmi1
- Lzcnt
- Popcnt
=> Mosa.TinyCoreLib: Implement small classes
